influxdb:
  image: influxdb:latest
  container_name: influxdb_latest
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'influxdb.env'
  volumes:
    - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro

telegraf:
  image: telegraf:latest
  container_name: telegraf_latest
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxdb